### ISSUE TITLE
Message of Note Saved even after note is empty

### ISSUE THREAD

**Issue by chintandesai49** [vishesh/sealnote#14]
After i trying to save an empty note it showed me the message "No point of saving empty Note" in plain  text note and immediately it showed me the Note saved.
I am attaching one zip in which i have attached one video.
[Seal Note Error.zip](https://github.com/vishesh/sealnote/files/117183/Seal.Note.Error.zip)

.

**Comment by vishesh** [comment]
Thanks for reporting.

NOTE: Reproducible when "Autosave" is disabled.

**Comment by mongakshay** [comment]
Yes even I faced that same error
