### ISSUE TITLE
Binary libraries are preventing implementing SealNote into F-Droid's repo

### ISSUE THREAD

**Issue by chadcurtis** [vishesh/sealnote#34]
For reference: https://f-droid.org/forums/topic/sealnote/

I was looking into apps that are stuck in the F-Droid submission queue, and wish to see where I could assist to push these processes forward. 

It seems that the binary libraries [here](https://github.com/vishesh/sealnote/tree/master/Sealnote/libs/armeabi-v7a) are the issue in this case, as they are precompiled items that could pose a potential security threat in the eyes of those that appreciate full transparency. I do not know how to proceed, however, so I was hoping you may have insight!

**Comment by vishesh** [comment]
@chadcurtis Those binaries belong to [sql-cipher](https://www.zetetic.net/sqlcipher/open-source/) project. It is an open source library, so we can try to remove these binaries and rather use original source to build them. Can be added as gradle task or something.

**Comment by chadcurtis** [comment]
Thanks @vishesh. Is this something you'd be willing to look into? If so, it would make the process of moving this into F-Droid go more smoothly. Thanks!

**Comment by vishesh** [comment]
@chadcurtis I would like to, however, I can't do that anytime soon. In other words I'm calling out for help! 

@akshatgoel Would you be interested in this?

**Comment by faruktoptas** [comment]
I removed binary libs with #35 sql-cipher is added with this dependency:
`compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'`

**Comment by vishesh** [comment]
Thanks @faruktoptas!

**Comment by chadcurtis** [comment]
Thank you for jumping on this so aptly, @faruktoptas.

I have re-submitted SealNote to the F-Droid queue [here](https://gitlab.com/fdroid/rfp/issues/59), but I noticed that they require the author to be notified of this inclusion (and to be supportive of it).

So, this is my notification! Are you fine with SealNote being part of the F-Droid library, @vishesh?

**Comment by vishesh** [comment]
@chadcurtis Yes I'll be happy to see Sealnote as part of F-Droid library.

**Comment by faruktoptas** [comment]
I think `commons-codec.jar` and `guava-r09.jar` should also be removed.

**Comment by vishesh** [comment]
@faruktoptas Yes right. Would you like to take a look at this? Or else, I can probably work on it this weekend among other things.

**Comment by chadcurtis** [comment]
@faruktoptas I've attempted to replace the jars with gradle dependencies in #39.

**Comment by vishesh** [comment]
Awesome! Merged the changes. Thanks @chadcurtis .
