### ISSUE TITLE
Feature request: import/export

### ISSUE THREAD

**Issue by netge** [vishesh/sealnote#36]
I am keeping several long-term notes that I carry across generations of devices and operating systems. For that it would be a prerequisite to have an import/export function to/from a simple and open file format, such as plaintext.

**Comment by akshatgoel** [comment]
@netge I am not sure about this one. While @vishesh  & I are very keen on improving current backup/restore behavior, we think storing notes in plaintext defeats the purpose of the app.

AFAIK, many of the android devices have simple note taking app in-built which has decent import/export functionalities in plaintext. I thought about having an additional option but again, giving an option to the user increases the choice paralysis. It also encourages people to store their notes on non-secure mediums.

**Comment by netge** [comment]
Then how should I get notes from a different app or device into sealnote?

Using the clipboard is a lot less secure than using import/export to an SD card that I overwrite afterwards I think!

I also have the policy that I never collect valuable data in apps that cannot export to an open exchange format. I learned it the hard way; at some point the data is just lost if there is no way to get it out!

**Comment by vishesh** [comment]
@netge You can use existing backup/restore functionality to export in an encrypted format. The file itself is sql-cipher database which is open-source, so its no technically closed and be read by third-party apps if they want to. It just makes it harder for novices to screw up by saving encrypted stuff in storage, dropbox or whatever.

**Comment by netge** [comment]
I think it would be enough to display a warning like "You are going to export data unencrypted. Do you want to continue?" Users who do not understand the meaning of this would probably not bother using an encrypted notepad, nor would they understand what happens when they copy to the clipboard, for example.

On the other hand reading data from sql-cipher means you have to write code. 99.9% of people cannot do that. What if the source/receiver app is closed source? It is also too specific a format to expect another app to implement import/export for it. Something like CSV would be more appropriate, IMO.
