### ISSUE TITLE
Github releases for stable versions

### ISSUE THREAD

**Issue by chadcurtis** [vishesh/sealnote#40]
Hello once more! It looks like SealNote has been accepted into the F-Droid repo, but they were curious about the [addition of stable version tags](https://gitlab.com/fdroid/rfp/issues/59#note_25059320).

It's an argument of ease for the maintainers, as it appears that someone will have to push new versions of the app to F-Droid manually if tagged releases are not present. Would you be interested in releasing in such a fashion?

Once more, thank you for your quick and kindly replies to these matters!

**Comment by vishesh** [comment]
Sure, we can do tagged releases. How does F-droid do ordering of tags, using dates or the tag name itself?

**Comment by chadcurtis** [comment]
Judging from [this documentation](https://f-droid.org/manual/fdroid.html#Auto-Update-Mode), F-Droid just requires releases tagged with the version number. So, only the tag name itself, if I'm gathering this correctly!

**Comment by vishesh** [comment]
Pushed first tag v0.8.7
