### ISSUE TITLE
Feature request: search within the note!

### ISSUE THREAD

**Issue by antiacid** [vishesh/sealnote#41]
Hi guys! Love the app, the only feature I and sure many others really need is a search function within the note to quickly locate stuff by the key word. Then I would never switch to any other app, this one would be all time best!

**Comment by akshatgoel** [comment]
Thanks for kind words @antiacid ! [Search feature](https://github.com/vishesh/sealnote/issues/3) is on our roadmap for long. We hope to deliver the same soon!
