### ISSUE TITLE
Hardcoded string makes sentence untranslatable

### ISSUE THREAD

**Issue by Tamarindo94** [vishesh/sealnote#58]
There is a hardcoded string in file SealnoteFragment.java, method onAdapterDataSetChanged(). This makes it impossible to translate the string without touching the code. The line I'm talking about is:
`mEmptyGeneric.setText(getActivity().getActionBar().getTitle() + " is empty!");`
https://github.com/vishesh/sealnote/blob/master/Sealnote/src/main/java/com/twistedplane/sealnote/fragment/SealnoteFragment.java#L182

I also noticed that, for dialogues where a "Cancel" button is present, the string for "Cancel" is not read from strings.xml but uses the OS default for the selected language

**Comment by vishesh** [comment]
@Tamarindo94 Thanks for reporting this. If you are translating this and are planning to submit a PR, you can include a fix for this. Otherwise, I will work on the fix.

**Comment by Tamarindo94** [comment]
Pull request sent

**Comment by vishesh** [comment]
@Tamarindo94 Thank you for fixing this!
