### ISSUE TITLE
Don't show actual screenshot on recent apps view

### ISSUE THREAD

**Issue by MakisH** [vishesh/sealnote#7]
Sealnote provides password protection and this works as expected inside the app. BUT, if I leave the app (e.g. with the back or home button), the last view is shown in the android recent apps list. This allows to see quite a big part of the encrypted information, without ever typing any password.

It would be nice if the app could immediately lock before going to the background, or always show a static image at recent apps view.

I have observed the same problem also in other "password-protected" apps, like dropbox.

**Comment by vishesh** [comment]
There is already a setting for a long time in app that disallows screenshots and thumbnail in window switchers.

**Comment by MakisH** [comment]
You are totally right! I hadn't realised the reason of this setting until now. Great job! :-D
